title: Ascendio
#logo:/assets/img/image1.png
#description : text below image
#show_downloads: true
theme: jekyll-theme-minimal
#baseurl: /home_page/_posts

lsi: false
safe: true
source: seekascendio.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
